name: PR

on:
  pull_request:
    branches:
      - master
      - '*-maintenance'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  hide:
    steps:
      - uses: int128/hide-comment-action@v1
        with:
          starts-with: "Do you want to test this code? Here you have an automated build:"
          ends-with: "WARNING: It may be unstable and result in corrupted configurations or data loss. Use only for testing!"
