name: PR

on:
  pull_request:
    branches:
      - master
      - '*-maintenance'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  artifact_links:
    name: Artifact links creator
    uses: ./.github/workflows/test1.yml
